name: json_shrink_widget
description: A widget to format json,support developer have a beatiful json viewer.

homepage: https://github.com/fastcode555/json_viewer.git
version: 1.1.3

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true