name: json_shrink_widget
description: A widget to format json.

homepage: https://github.com/fastcode555/json_viewer.git
version: 1.0.2

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image:
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true